import type { Suggestion, SuggestionIcon } from '../../../types';

// ============================================
// Autocomplete Suggestions Database
// ============================================

export const SUGGESTION_ICONS: Record<string, SuggestionIcon> = {
  keyword: { icon: '⬜', color: 'text-[#569cd6]' },
  function: { icon: '🟪', color: 'text-[#dcdcaa]' },
  variable: { icon: '🟦', color: 'text-[#9cdcfe]' },
  method: { icon: '🟣', color: 'text-[#dcdcaa]' },
  property: { icon: '⬛', color: 'text-[#9cdcfe]' },
  snippet: { icon: '🔲', color: 'text-[#ce9178]' },
  class: { icon: '🟧', color: 'text-[#4ec9b0]' },
  interface: { icon: '🟡', color: 'text-[#4ec9b0]' },
  module: { icon: '📦', color: 'text-[#d4d4d4]' },
  constant: { icon: '🔵', color: 'text-[#4fc1ff]' },
};

export const SUGGESTION_DB: Suggestion[] = [
  // Keywords
  { word: 'const', kind: 'keyword', detail: 'keyword' },
  { word: 'let', kind: 'keyword', detail: 'keyword' },
  { word: 'var', kind: 'keyword', detail: 'keyword' },
  { word: 'function', kind: 'keyword', detail: 'keyword' },
  { word: 'return', kind: 'keyword', detail: 'keyword' },
  { word: 'if', kind: 'keyword', detail: 'keyword' },
  { word: 'else', kind: 'keyword', detail: 'keyword' },
  { word: 'for', kind: 'keyword', detail: 'keyword' },
  { word: 'while', kind: 'keyword', detail: 'keyword' },
  { word: 'class', kind: 'keyword', detail: 'keyword' },
  { word: 'import', kind: 'keyword', detail: 'keyword' },
  { word: 'export', kind: 'keyword', detail: 'keyword' },
  { word: 'default', kind: 'keyword', detail: 'keyword' },
  { word: 'from', kind: 'keyword', detail: 'keyword' },
  { word: 'async', kind: 'keyword', detail: 'keyword' },
  { word: 'await', kind: 'keyword', detail: 'keyword' },
  { word: 'try', kind: 'keyword', detail: 'keyword' },
  { word: 'catch', kind: 'keyword', detail: 'keyword' },
  { word: 'finally', kind: 'keyword', detail: 'keyword' },
  { word: 'throw', kind: 'keyword', detail: 'keyword' },
  { word: 'new', kind: 'keyword', detail: 'keyword' },
  { word: 'this', kind: 'keyword', detail: 'keyword' },
  { word: 'typeof', kind: 'keyword', detail: 'keyword' },
  { word: 'instanceof', kind: 'keyword', detail: 'keyword' },
  { word: 'interface', kind: 'keyword', detail: 'keyword' },
  { word: 'type', kind: 'keyword', detail: 'keyword' },
  { word: 'extends', kind: 'keyword', detail: 'keyword' },
  { word: 'implements', kind: 'keyword', detail: 'keyword' },
  { word: 'switch', kind: 'keyword', detail: 'keyword' },
  { word: 'case', kind: 'keyword', detail: 'keyword' },
  { word: 'break', kind: 'keyword', detail: 'keyword' },
  { word: 'continue', kind: 'keyword', detail: 'keyword' },
  { word: 'void', kind: 'keyword', detail: 'keyword' },
  { word: 'delete', kind: 'keyword', detail: 'keyword' },
  { word: 'enum', kind: 'keyword', detail: 'keyword' },
  { word: 'static', kind: 'keyword', detail: 'keyword' },
  { word: 'readonly', kind: 'keyword', detail: 'keyword' },
  { word: 'abstract', kind: 'keyword', detail: 'keyword' },
  { word: 'public', kind: 'keyword', detail: 'keyword' },
  { word: 'private', kind: 'keyword', detail: 'keyword' },
  { word: 'protected', kind: 'keyword', detail: 'keyword' },
  
  // Functions / Methods
  { word: 'console', kind: 'variable', detail: 'var console: Console' },
  { word: 'console.log', kind: 'method', detail: '(method) Console.log(...data: any[]): void' },
  { word: 'console.error', kind: 'method', detail: '(method) Console.error(...data: any[]): void' },
  { word: 'console.warn', kind: 'method', detail: '(method) Console.warn(...data: any[]): void' },
  { word: 'document', kind: 'variable', detail: 'var document: Document' },
  { word: 'document.getElementById', kind: 'method', detail: '(method) Document.getElementById(elementId: string): HTMLElement | null' },
  { word: 'document.querySelector', kind: 'method', detail: '(method) Document.querySelector(selectors: string): Element | null' },
  { word: 'document.createElement', kind: 'method', detail: '(method) Document.createElement(tagName: string): HTMLElement' },
  { word: 'window', kind: 'variable', detail: 'var window: Window & typeof globalThis' },
  { word: 'setTimeout', kind: 'function', detail: '(function) setTimeout(handler: Function, timeout?: number): number' },
  { word: 'setInterval', kind: 'function', detail: '(function) setInterval(handler: Function, timeout?: number): number' },
  { word: 'clearTimeout', kind: 'function', detail: '(function) clearTimeout(id: number): void' },
  { word: 'clearInterval', kind: 'function', detail: '(function) clearInterval(id: number): void' },
  { word: 'addEventListener', kind: 'method', detail: '(method) addEventListener(type: string, listener: Function): void' },
  { word: 'removeEventListener', kind: 'method', detail: '(method) removeEventListener(type: string, listener: Function): void' },
  { word: 'fetch', kind: 'function', detail: '(function) fetch(input: RequestInfo, init?: RequestInit): Promise<Response>' },
  { word: 'Promise', kind: 'class', detail: 'class Promise<T>' },
  { word: 'Array', kind: 'class', detail: 'class Array<T>' },
  { word: 'Object', kind: 'class', detail: 'class Object' },
  { word: 'String', kind: 'class', detail: 'class String' },
  { word: 'Number', kind: 'class', detail: 'class Number' },
  { word: 'Boolean', kind: 'class', detail: 'class Boolean' },
  { word: 'Map', kind: 'class', detail: 'class Map<K, V>' },
  { word: 'Set', kind: 'class', detail: 'class Set<T>' },
  { word: 'JSON', kind: 'variable', detail: 'var JSON: JSON' },
  { word: 'JSON.parse', kind: 'method', detail: '(method) JSON.parse(text: string): any' },
  { word: 'JSON.stringify', kind: 'method', detail: '(method) JSON.stringify(value: any): string' },
  { word: 'Math', kind: 'variable', detail: 'var Math: Math' },
  { word: 'Math.random', kind: 'method', detail: '(method) Math.random(): number' },
  { word: 'Math.floor', kind: 'method', detail: '(method) Math.floor(x: number): number' },
  { word: 'Math.ceil', kind: 'method', detail: '(method) Math.ceil(x: number): number' },
  { word: 'Math.round', kind: 'method', detail: '(method) Math.round(x: number): number' },
  
  // React specific
  { word: 'useState', kind: 'function', detail: '(function) useState<S>(initialState: S): [S, Dispatch<SetStateAction<S>>]' },
  { word: 'useEffect', kind: 'function', detail: '(function) useEffect(effect: EffectCallback, deps?: DependencyList): void' },
  { word: 'useCallback', kind: 'function', detail: '(function) useCallback<T>(callback: T, deps: DependencyList): T' },
  { word: 'useMemo', kind: 'function', detail: '(function) useMemo<T>(factory: () => T, deps: DependencyList): T' },
  { word: 'useRef', kind: 'function', detail: '(function) useRef<T>(initialValue: T): MutableRefObject<T>' },
  { word: 'useContext', kind: 'function', detail: '(function) useContext<T>(context: Context<T>): T' },
  { word: 'useReducer', kind: 'function', detail: '(function) useReducer<R>(reducer: R, initialArg: any): [any, Dispatch<any>]' },
  { word: 'React', kind: 'module', detail: 'module "react"' },
  { word: 'ReactDOM', kind: 'module', detail: 'module "react-dom"' },
  { word: 'Component', kind: 'class', detail: 'class React.Component<P, S>' },
  
  // Array methods
  { word: 'map', kind: 'method', detail: '(method) Array<T>.map(callbackfn: Function): U[]' },
  { word: 'filter', kind: 'method', detail: '(method) Array<T>.filter(predicate: Function): T[]' },
  { word: 'reduce', kind: 'method', detail: '(method) Array<T>.reduce(callbackfn: Function): T' },
  { word: 'forEach', kind: 'method', detail: '(method) Array<T>.forEach(callbackfn: Function): void' },
  { word: 'find', kind: 'method', detail: '(method) Array<T>.find(predicate: Function): T | undefined' },
  { word: 'findIndex', kind: 'method', detail: '(method) Array<T>.findIndex(predicate: Function): number' },
  { word: 'includes', kind: 'method', detail: '(method) Array<T>.includes(searchElement: T): boolean' },
  { word: 'push', kind: 'method', detail: '(method) Array<T>.push(...items: T[]): number' },
  { word: 'pop', kind: 'method', detail: '(method) Array<T>.pop(): T | undefined' },
  { word: 'slice', kind: 'method', detail: '(method) Array<T>.slice(start?: number, end?: number): T[]' },
  { word: 'splice', kind: 'method', detail: '(method) Array<T>.splice(start: number, deleteCount?: number): T[]' },
  { word: 'length', kind: 'property', detail: '(property) Array<T>.length: number' },
  { word: 'toString', kind: 'method', detail: '(method) toString(): string' },
  { word: 'valueOf', kind: 'method', detail: '(method) valueOf(): Object' },
  
  // Common variables
  { word: 'true', kind: 'constant', detail: 'boolean' },
  { word: 'false', kind: 'constant', detail: 'boolean' },
  { word: 'null', kind: 'constant', detail: 'null' },
  { word: 'undefined', kind: 'constant', detail: 'undefined' },
  { word: 'NaN', kind: 'constant', detail: 'number' },
  { word: 'Infinity', kind: 'constant', detail: 'number' },
  
  // String methods
  { word: 'split', kind: 'method', detail: '(method) String.split(separator: string): string[]' },
  { word: 'join', kind: 'method', detail: '(method) Array<string>.join(separator?: string): string' },
  { word: 'trim', kind: 'method', detail: '(method) String.trim(): string' },
  { word: 'replace', kind: 'method', detail: '(method) String.replace(searchValue: string, replaceValue: string): string' },
  { word: 'substring', kind: 'method', detail: '(method) String.substring(start: number, end?: number): string' },
  { word: 'toLowerCase', kind: 'method', detail: '(method) String.toLowerCase(): string' },
  { word: 'toUpperCase', kind: 'method', detail: '(method) String.toUpperCase(): string' },
  { word: 'charAt', kind: 'method', detail: '(method) String.charAt(pos: number): string' },
  { word: 'charCodeAt', kind: 'method', detail: '(method) String.charCodeAt(index: number): number' },
  { word: 'startsWith', kind: 'method', detail: '(method) String.startsWith(searchString: string): boolean' },
  { word: 'endsWith', kind: 'method', detail: '(method) String.endsWith(searchString: string): boolean' },
  { word: 'padStart', kind: 'method', detail: '(method) String.padStart(maxLength: number, fillString?: string): string' },
  { word: 'padEnd', kind: 'method', detail: '(method) String.padEnd(maxLength: number, fillString?: string): string' },
  { word: 'repeat', kind: 'method', detail: '(method) String.repeat(count: number): string' },
  { word: 'match', kind: 'method', detail: '(method) String.match(regexp: RegExp): RegExpMatchArray | null' },
  { word: 'search', kind: 'method', detail: '(method) String.search(regexp: RegExp): number' },
];
